[
  {
    type: 'gif',
    id: '26xBLq0QJdxy57CV2',
    url: 'https://giphy.com/gifs/cat-cats-illustrator-26xBLq0QJdxy57CV2',
    slug: 'cat-cats-illustrator-26xBLq0QJdxy57CV2',
    bitly_gif_url: 'http://gph.is/2ldlMTT',
    bitly_url: 'http://gph.is/2ldlMTT',
    embed_url: 'https://giphy.com/embed/26xBLq0QJdxy57CV2',
    username: 'jeanniephan',
    source: '',
    title: 'Cat Lady GIF by Jeannie Phan',
    rating: 'g',
    content_url: '',
    source_tld: '',
    source_post_url: '',
    is_sticker: 0,
    import_datetime: '2017-02-07 00:39:23',
    trending_datetime: '2018-08-27 05:30:02',
    images: {
      original: [Object],
      downsized: [Object],
      downsized_large: [Object],
      downsized_medium: [Object],
      downsized_small: [Object],
      downsized_still: [Object],
      fixed_height: [Object],
      fixed_height_downsampled: [Object],
      fixed_height_small: [Object],
      fixed_height_small_still: [Object],
      fixed_height_still: [Object],
      fixed_width: [Object],
      fixed_width_downsampled: [Object],
      fixed_width_small: [Object],
      fixed_width_small_still: [Object],
      fixed_width_still: [Object],
      looping: [Object],
      original_still: [Object],
      original_mp4: [Object],
      preview: [Object],
      preview_gif: [Object],
      preview_webp: [Object],
      '480w_still': [Object]
    },
    user: {
      avatar_url: 'https://media3.giphy.com/avatars/jeanniephan/UC8EWvp5AlV1.gif',
      banner_image: '',
      banner_url: '',
      profile_url: 'https://giphy.com/jeanniephan/',
      username: 'jeanniephan',
      display_name: 'Jeannie Phan',
      description: 'Freelance illustrator, hopeful green thumb, genuine cat lady',
      instagram_url: 'https://instagram.com/jeanniephan',
      website_url: 'http://www.jeanniephan.com',
      is_verified: true
    },
    analytics_response_payload: 'e=Z2lmX2lkPTI2eEJMcTBRSmR4eTU3Q1YyJmV2ZW50X3R5cGU9R0lGX1NFQVJDSCZjaWQ9YzI2MDVmN2F1ZGZxMWtqZjZjdnY2aGphMmJmbW1iNjRtampsbGxnN2p2MndqdW5hJmN0PWc',
    analytics: { onload: [Object], onclick: [Object], onsent: [Object] }
  }
]
